[2025-02-07T14:45:18.032+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-07T14:45:18.137+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_training_dag.task_train_model scheduled__2025-02-07T14:24:56.073886+00:00 [queued]>
[2025-02-07T14:45:18.169+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_training_dag.task_train_model scheduled__2025-02-07T14:24:56.073886+00:00 [queued]>
[2025-02-07T14:45:18.169+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 1
[2025-02-07T14:45:18.213+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): task_train_model> on 2025-02-07 14:24:56.073886+00:00
[2025-02-07T14:45:18.250+0000] {standard_task_runner.py:72} INFO - Started process 105 to run task
[2025-02-07T14:45:18.325+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'my_training_dag', 'task_train_model', 'scheduled__2025-02-07T14:24:56.073886+00:00', '--job-id', '966', '--raw', '--subdir', 'DAGS_FOLDER/training_dag.py', '--cfg-path', '/tmp/tmp_zv2sug9']
[2025-02-07T14:45:18.328+0000] {standard_task_runner.py:105} INFO - Job 966: Subtask task_train_model
[2025-02-07T14:45:18.674+0000] {task_command.py:467} INFO - Running <TaskInstance: my_training_dag.task_train_model scheduled__2025-02-07T14:24:56.073886+00:00 [running]> on host 439a689a0751
[2025-02-07T14:45:18.890+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='my_training_dag' AIRFLOW_CTX_TASK_ID='task_train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-02-07T14:24:56.073886+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-07T14:24:56.073886+00:00'
[2025-02-07T14:45:18.892+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-07T14:45:18.893+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-07T14:45:18.898+0000] {logging_mixin.py:190} INFO - Current task name:task_train_model state:running start_date:2025-02-07 14:45:18.139125+00:00
[2025-02-07T14:45:18.899+0000] {logging_mixin.py:190} INFO - Dag name:my_training_dag and current dag run status:running
[2025-02-07T14:45:18.900+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-07T14:45:18.903+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-07T14:45:18.905+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /root/airflow/train.py']
[2025-02-07T14:45:18.946+0000] {subprocess.py:99} INFO - Output:
[2025-02-07T14:45:22.987+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-07T14:45:23.023+0000] {process_utils.py:132} INFO - Sending 15 to group 105. PIDs of all processes in the group: [107, 105]
[2025-02-07T14:45:23.023+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 105
[2025-02-07T14:45:23.025+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-02-07T14:45:23.029+0000] {subprocess.py:117} INFO - Sending SIGTERM signal to process group
[2025-02-07T14:45:23.078+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/operators/bash.py", line 257, in execute
    result = self._run_inline_command(bash_path=bash_path, env=env)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/operators/bash.py", line 284, in _run_inline_command
    return self.subprocess_hook.run_command(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/hooks/subprocess.py", line 104, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-02-07T14:45:23.092+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-07T14:45:23.092+0000] {logging_mixin.py:190} INFO - Task start:2025-02-07 14:45:18.139125+00:00 end:2025-02-07 14:45:23.090922+00:00 duration:4.951797
[2025-02-07T14:45:23.093+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): task_train_model> dag:<DAG: my_training_dag> dagrun:<DagRun my_training_dag @ 2025-02-07 14:24:56.073886+00:00: scheduled__2025-02-07T14:24:56.073886+00:00, state:running, queued_at: 2025-02-07 14:41:37.334744+00:00. externally triggered: False>
[2025-02-07T14:45:23.093+0000] {logging_mixin.py:190} INFO - Failure caused by Task received SIGTERM signal
[2025-02-07T14:45:23.094+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=my_training_dag, task_id=task_train_model, run_id=scheduled__2025-02-07T14:24:56.073886+00:00, execution_date=20250207T142456, start_date=20250207T144518, end_date=20250207T144523
[2025-02-07T14:45:23.111+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
